_name_or_path:
    value: Qwen/Qwen2.5-0.5B-Instruct
_wandb:
    value:
        cli_version: 0.23.1
        e:
            mrubbemtb6nodcan7dswmfpiik73jzf6:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "119830216704"
                        used: "16028024832"
                email: vedangavaghade01@gmail.com
                executable: /home/vavaghad/miniconda/envs/nlp_fix_env/bin/python3
                git:
                    commit: cb9eb6016819907e1c74acacfb5ee4a732f50d6b
                    remote: https://github.com/Vedang1308/RLAIF.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-ca564560-9627-a96f-ba6d-6a753ee4cdfa
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-262a3d2c-f88a-c4dd-75f3-e5399df62254
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9e7db306-38b8-659b-fa12-b8d1a15c2d81
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-7ffe4614-ff72-6951-997a-12213dbbd31a
                host: sg049
                memory:
                    total: "540627021824"
                os: Linux-4.18.0-553.77.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /home/vavaghad/RLAIF/RLAIF/train.py
                python: CPython 3.10.19
                root: /home/vavaghad/RLAIF/RLAIF
                slurm:
                    cluster_name: sol
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    export_env: NONE
                    get_user_env: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: class_cse576fall2025
                    job_cpus_per_node: "4"
                    job_end_time: "1766192353"
                    job_gid: "88888713"
                    job_gpus: "1"
                    job_id: "42777656"
                    job_name: rlaif-qwen-0.5b
                    job_nodelist: sg049
                    job_num_nodes: "1"
                    job_partition: public
                    job_qos: class
                    job_start_time: "1766185153"
                    job_uid: "3287262"
                    job_user: vavaghad
                    jobid: "42777656"
                    localid: "0"
                    mem_per_node: "24000"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: sg049
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/vavaghad/RLAIF/RLAIF
                    submit_host: sg025
                    task_pid: "812737"
                    tasks_per_node: "1"
                    topology_addr: sg049
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2025-12-19T22:59:54.815853Z"
                writerId: mrubbemtb6nodcan7dswmfpiik73jzf6
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 7
                - 13
                - 66
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.57.3
            "9":
                "1": transformers_trainer
            "12": 0.23.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen2ForCausalLM
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
batch_size:
    value: 8
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 151643
chunk_size_feed_forward:
    value: 0
cliprange:
    value: 0.2
cliprange_value:
    value: 0.2
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_num_proc:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
ds3_gather_for_generation:
    value: true
dtype:
    value: float32
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exp_name:
    value: ppo_config
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gamma:
    value: 1
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_size:
    value: 896
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 4864
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
kl_coef:
    value: 0.05
kl_estimator:
    value: k1
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
lam:
    value: 0.95
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 1.41e-05
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_batch_size:
    value: 8
local_mini_batch_size:
    value: 8
local_rank:
    value: 0
local_rollout_forward_batch_size:
    value: 64
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: trainer_output/runs/Dec19_15-59-47_sg049
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 32768
max_steps:
    value: -1
max_window_layers:
    value: 21
metric_for_best_model:
    value: null
micro_batch_size:
    value: 8
min_length:
    value: 0
mini_batch_size:
    value: 8
missing_eos_penalty:
    value: null
model_adapter_name:
    value: null
model_type:
    value: qwen2
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 14
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 24
num_key_value_heads:
    value: 2
num_mini_batches:
    value: 1
num_ppo_epochs:
    value: 4
num_return_sequences:
    value: 1
num_sample_generations:
    value: 10
num_total_batches:
    value: 38
num_train_epochs:
    value: 3
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: trainer_output
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
parallelism_config:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
ref_adapter_name:
    value: null
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
response_length:
    value: 53
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
reward_model_path:
    value: EleutherAI/pythia-160m
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value: null
rope_theta:
    value: 1e+06
run_name:
    value: ppo_config__42__1766185194
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
sft_model_path:
    value: EleutherAI/pythia-160m
skip_memory_metrics:
    value: true
sliding_window:
    value: null
stop_token:
    value: <STOP_TOKEN>
stop_token_id:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 0.7
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
total_episodes:
    value: 300
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.3
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
vf_coef:
    value: 0.1
vocab_size:
    value: 151936
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0
whiten_rewards:
    value: false
world_size:
    value: 1
